# Generated by Django 3.0.4 on 2020-04-12 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0004_auto_20200412_1003'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='image',
            field=models.URLField(blank=True, default=None),
        ),
    ]
